apiVersion: v1
kind: Pod
metadata:
  name: tools
spec:
  containers:
  - name: tools-container
    image: image-registry.openshift-image-registry.svc.cluster.local:5000/custom-udi-image/custom-udi-image:latest